project:
  type: website
  output-dir: docs

website:
  title: "MT412 E-Portfolio - Chloe Downes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About Me.qmd
      - Media.qmd
      - Projects.qmd
    tools:
      - icon: github
        href: https://github.com/chloed77/MT412-E-Portfolio
  page-footer: 
    left: "Chloe Downes, 2024"    
    right: "Built with [Quorto](https://quarto.org/)" 

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true




