---
title: "About Me"
---

## Bibliography 
Hello! My name is Chloe Downes. I am 24 years old and I am currently a final year student in Dublin City University. For my final year, I am currently specializing in data analytics in addition to completing financial modules. I initially completed my work experience in the finance sector, and upon working in this sector, I discovered I am much more drawn to the interchangeability and modernization of data analytics. 

I have decided to peruse the data analytics specialism as I am very interested in the new opportunities of this sector. The various avenues available and the growing speed of this area of business is very appealing to me. I am drawn to a career in data analytics due to its dynamic nature and its potential to drive informed decision-making across all aspects of business. The ability to sift through vast amounts of data, uncover meaningful insights, and translate them into actionable strategies excites me. Moreover, I am fascinated by the prospect of using advanced analytically tools and techniques to solve complex problems and optimize processes. Data analytics not only offers a rewarding career path but also allows me to contribute to solving real-world challenges, making a tangible impact on businesses and society as a whole. I further wish to grow into this area of business.


## Resume


## Hobbies
- football
- travel
- music
